excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://samparsky.github.io
title: Omidiora Samuel
tagline: Making the world a better place
description: I am a part 4 student of Obafemi Awolowo University. Currently a Devops Engineer Intern at Terragon LTD. You can contact me @ samparsky@gmail.com
email: samparsky@gmail.com
paginate: 5
