excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://samparsky.github.io
title: Omidiora Samuel
tagline: Making the world a better place
description: Hi there, My name is Samuel Omidiora, a part 4 student of Obafemi Awolowo University. Currently an Intern Software Engineer at Terragon LTD.
paginate: 5